config/routes.rb
Rails.application.routes.draw do
  get 'administrations/index'

  get 'administrations/hours'

  get 'administrations/selec_doctor'

  get 'administrations/block'

  get 'administrations/add_block'

  get 'administrations/message1'

  get 'administrations/message2'

  get 'administrations/message3'

  get 'my_hours/mishoras'

  get 'my_hours/mishoras2'

  get 'my_hours/message1'

  get 'search/index'

  get 'take_hours/index'

  get 'take_hours/show'

  get 'take_hours/show2'

  get 'take_hours/show3'

  get 'take_hours/message1'

  get 'search_specialties/index'

  get 'search_medics/index'

  get 'users/index'

  get 'establishments/index'

  get 'establishments/show'

  get 'welcome/index'

  get 'reports/gestion' => 'reports#gestion'

  get 'reports/solicitudes' => 'reports#solicitudes'

  get 'reports/asistenciaAPS' => 'reports#asistenciaAPS'

  get 'reports/asistenciaGENERAL' => 'reports#asistenciaGENERAL'

  get 'reports/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  match ':controller(/:action(/:id))', :via => [:get, :post]
   root 'welcome#index'

end

app/controllers/administrations_controller.rb
class AdministrationsController < ApplicationController
	before_filter :authenticate_user!
  	before_filter do 
    		redirect_to new_user_session_path unless current_user && (current_user.admin? || current_user.functionary?)
  	end
  def index
  end

  def hours
	if current_user.admin?
		#todas las horas reservadas
		@horas = ReservedHour.find_by_sql("select * from reserved_hours where reserved_hours.RH_STATE = true")
		#todos los bloques de atención
		@abs = AttentionBlock.find_by_sql("select * from attention_blocks where AB_AVAILABLE = true")
	else
		funcionario = Employee.find_by_sql("select * from employees where user_id = '#{current_user.user_id}'")
		
		#mostrar las horas del establecimiento del funcionario
		@horas = ReservedHour.find_by_sql("select * from reserved_hours rh inner join attention_blocks ab on ab.AB_ID = rh.AB_ID inner join doctors d on d.doctor_id = ab.doctor_id where d.EST_ID = '#{funcionario[0].EST_ID}' and rh.RH_STATE = true")
		@abs = AttentionBlock.find_by_sql("select * from attention_blocks ab inner join doctors d on d.doctor_id = ab.doctor_id where d.EST_ID = '#{funcionario[0].EST_ID}' and ab.AB_AVAILABLE = true")
	end
		#los usuarios que son pacientes
		@usuarios = User.find_by_sql("select * from users u inner join patients p on p.user_id = u.user_id")
		#pacientes
		@pacientes = Patient.find_by_sql("select * from patients")

  end

  def cancelar
	ReservedHour.cancelar params[:id_hora]
	#Mensaje que dice "hora eliminada"
	redirect_to administrations_message3_path
  end

  def selec_doctor
	if current_user.admin?
		@doctors = Doctor.find_by_sql("select * from doctors")
		#usuarios que son doctores
	else
		funcionario = Employee.find_by_sql("select * from employees where user_id = '#{current_user.user_id}'")
		@doctors = Doctor.find_by_sql("select * from doctors where EST_ID = '#{funcionario[0].EST_ID}'")
	end
		@usuarios = User.find_by_sql("select * from users u inner join doctors d on d.user_id = u.user_id")
  end

	#seleccionar los bloques del doctor
  def block
	@bloques = AttentionBlock.find_by_sql("select * from attention_blocks ab where ab.doctor_id = '#{params[:doctor_id]}' and ab.AB_AVAILABLE = true")
	@specs = Specialty.find_by_sql("select * from specialties")
	@doc_id = params[:doctor_id]
  end

  def deshabilitar
	AttentionBlock.deshabilitar(params[:ab_id])
	redirect_to administrations_message1_path
  end

  def add_block
	@doctor = User.find_by_sql("select * from users u inner join doctors d on d.user_id = u.user_id where d.doctor_id = '#{params[:doctor_id]}'")
	@specs = Specialty.find_by_sql("select * from specialties s inner join doctor_specialties ds on ds.SPEC_ID = s.SPEC_ID inner join doctors d on d.doctor_id = ds.doctor_id where d.doctor_id = '#{params[:doctor_id]}'")

  end

  def agregar_bloque
	fecha = params[:fecha]["(1i)"]+"-"+params[:fecha]["(2i)"]+"-"+params[:fecha]["(3i)"]
	hora_inicio = params[:hora_inicio]["(4i)"]+":"+params[:hora_inicio]["(5i)"]
	hora_fin = params[:hora_fin]["(4i)"]+":"+params[:hora_fin]["(5i)"]
	
	AttentionBlock.crear(params[:doctor_id], fecha, hora_inicio, hora_fin, params[:eficiencia], params[:spec_id])

	#Mensaje que dice "bloque creado"
	redirect_to administrations_message2_path
  end

  def message1
  	#Mensaje de Bloque eliminado Exitosamente
  end

  def message2
  	#Mensaje de Bloque creado Exitosamente
  end

  def message3
  	#Mensaje de HORA eliminada Exitosamente
  end

  def confirmarAsistencia
  	#Confirma una asistencia
  	ReservedHour.confirmarAsistencia(params[:id_hora])
  	#Redirige a la pagina anterior
  	redirect_to administrations_hours_path
  end

  def permisos
  		@users = User.find_by_sql("select * from users") 
  		@ests = Establishment.find_by_sql("select * from establishments")
  		@specs = Specialty.find_by_sql("select * from specialties")
  end

end

app/helpers/administrations_helper.rb
module AdministrationsHelper
end

app/views/administrations/add_block.html.erb
<section id="contact-info">
  <div class="center"  style = "padding-bottom: 0px">                
    <h2>Agregar nuevo Bloque.</h2>
    <p class="lead">Doctor <%=@doctor[0].user_NAMES %></p>
  </div>  
</section>

<!-- Form Tag -->
<%= form_tag url_for(:controller => "administrations", :action => 'agregar_bloque'), method: "get"  do %>

<body>  

    <div class="main-login main-center">
        <form class="form-horizontal" method="post" action="#">
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Fecha del Bloque (Día, Mes, Año)</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= hidden_field_tag :doctor_id, @doctor[0].doctor_id %>
                <%= date_select(:fecha, "", start_year: 2016, use_month_numbers: true, order: [:day, :month, :year])%>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Hora de Inicio</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= time_select :hora_inicio, '', {minute_step: 30}, prompt: {hour: 'hora', minute: 'minutos'}%>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Hora de Fin</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= time_select :hora_fin, '', {minute_step: 30}, prompt: {hour: 'hora', minute: 'minutos'}%>
              </div>
            </div>
          </div>
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Eficiencia Por Hora (De 1 a 6)</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= number_field_tag(:eficiencia, nil, in: 1...7) %>
              </div>
            </div>
          </div> 
          <div class="form-group">
            <label for="name" class="cols-sm-2 control-label">Especialidad del Bloque</label>
            <div class="cols-sm-10">
              <div class="input-group">
                <%= select_tag(:spec_id, options_from_collection_for_select(@specs, :SPEC_ID, :SPEC_NAME))%></br>
              </div>
            </div>
          </div>
          <div class="form-group ">
                <center><button type="submit_tag" class="btn btn-primary btn-lg btn-block login-button">Agregar</button></center>
          </div>
        </form>
    </div>
  </div>
</body>
<%end%>

app/views/administrations/block.html.erb
<section id="contact-info">
  <div class="center">                
    <h2>Administrar Bloques</h2>
    <p class="lead">Puede eliminar un bloque de atención con el botón "Deshabilitar", o agregar uno nuevo utilizando el boton de la parte inferior de  la tabla. </p>
  </div>  
</section>

<table>
  <tr>
    <th>n° Bloque</th>
    <th>Fecha</th>
    <th>Hora inicio</th>
    <th>Hora término</th>
    <th>Especialidad</th>
    <th>Acción</th>
  </tr>
  <% @bloques.each_with_index do |b, index|%>
    <% @specs.each do |s| %>
      <% if b.SPEC_ID == s.SPEC_ID %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= b.AB_DATE %></td>
          <td><%= b.AB_START_TIME.strftime('%H:%M') %></td>
          <td><%= b.AB_FINISH_TIME.strftime('%H:%M') %></td>
          <td><%= s.SPEC_NAME %></td>
          <td><%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Deshabilitar</button>".html_safe, {:action => 'deshabilitar', :ab_id => b.AB_ID} %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
</table>

<div class="search-center">
      <%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Agregar nuevo bloque de atención</button>".html_safe, {:action => 'add_block', :doctor_id => @doc_id} %>
</div>

app/views/administrations/hours.html.erb
<section id="about-us">
	<div class = "container" >
		<div class="center wow fadeInDown">
			<h2>Administrar horas reservadas</h2>
		</div>
	</div>
</section>

<% if @horas.count != 0 %>
	<table>
		<tr>
			<th>Fecha</th>
			<th>Hora</th>
			<th>Paciente</th>
			<th>Confirmar Asistencia</th>
			<th>Cancelar hora</th>
		</tr>
		<% @horas.each do |f| %>
			<% @abs.each do |a| %>
				<% @usuarios.each do |u| %>
					<% @pacientes.each do |p| %>
						<% if (f.AB_ID == a.AB_ID && f.patient_id == p.patient_id && u.user_id == p.user_id) %>
							<tr>
								<td><%= a.AB_DATE %></td>
								<td><%= f.RH_START_TIME.strftime('%H:%M')%></td>
								<td><%= u.user_NAMES%> <%= u.user_LASTNAME1%> <%= u.user_LASTNAME2%></td>
								<td>
								<%if(f.RH_ASSISTANCE == false) %>
									<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Confirmar Asistencia</button>".html_safe, {:action => 'confirmarAsistencia', :id_hora => f.RH_ID} %>
								<% else%>
									Esta hora ya ha sido Confirmada
								<% end %>
								</td>
								<td><%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Cancelar</button>".html_safe, {:action => 'cancelar', :id_hora => f.RH_ID} %></td>
							</tr>
						<% end %>
					<% end %>		
				<% end %>
			<% end %>
		<% end %>
	</table>
<% else %>
	<div class="center wow fadeInDown">
		<p class="lead"></br>No hay horas Reservadas</br></p>
		<div class="search-center">
			<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Volver Atrás</button>".html_safe, administrations_index_path %>
		</div>
	</div>
<% end %>

app/views/administrations/index.html.erb
<body>
	<section id="about-us">
		<div class = "container" >
			<div class="center wow fadeInDown">
				<h2> ¿Que desea administrar?</h2>
			</div>
			 <div class="main-login search-center">
				<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Administrar horas</button>".html_safe, administrations_hours_path %>
				<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Administrar bloques de atención</button>".html_safe, administrations_selec_doctor_path %>
			</div>
		</div>
	</section>
</body>

app/views/administrations/message1.html.erb
<body>
    <section id="error" class="container text-center">
    	<section id="about-us">
			<div class = "container" >
				<div class="center wow fadeInDown">
        			<h1>Bloque Eliminado con éxito</h1>
				</div>
			</div>
	   </section>
        <p></br></br>Recuerde que puede continuar agregando o eliminando bloques en "Servicios", "Administrar", "Administrar Horas de Atencion".</p>
        <%= link_to "<button class='btn btn-primary'>Volver a la Página Principal</button>".html_safe,  welcome_index_path %>
    </section><!--/#Mensaje-->
</body>

app/views/administrations/message2.html.erb
<body>
    <section id="error" class="container text-center">
    	<section id="about-us">
			<div class = "container" >
				<div class="center wow fadeInDown">
        			<h1>Bloque Creado con éxito</h1>
				</div>
			</div>
	</section>
        <p></br></br>Recuerde que puede continuar agregando o eliminando bloques en "Servicios", "Administrar", "Administrar Horas de Atencion".</p>
        <%= link_to "<button class='btn btn-primary'>Volver a la Página Principal</button>".html_safe,  welcome_index_path %>
    </section><!--/#error-->
</body>

app/views/administrations/message3.html.erb
<body>
    <section id="error" class="container text-center">
    	<section id="about-us">
			<div class = "container" >
				<div class="center wow fadeInDown">
        			<h1>Hora Eliminada con éxito</h1>
				</div>
			</div>
	</section>
        <p></br></br>Puede continuar eliminando horas si presiona el botón "Volver Atrás".</p>
        <%= link_to "<button class='btn btn-primary'>Volver Atrás</button>".html_safe,  administrations_hours_path %>
        <%= link_to "<button class='btn btn-primary'>Volver a la Página Principal</button>".html_safe,  welcome_index_path %>
    </section><!--/#error-->
</body>

app/views/administrations/selec_doctor.html.erb
<section id="contact-info"><div class="center">                
    <h2>Administrar Bloques</h2>
    <p class="lead">Seleccione un doctor para editar su agenda</p>
</div></section>

<table>
	<tr>
		<th>Nombre</th>
		<th>Editar</th>
	</tr>
	<% @usuarios.each do |u|%>
		<% @doctors.each do |d|%>
			<% if u.user_id == d.user_id %>
				<tr>
					<td><%= u.user_NAMES%> <%= u.user_LASTNAME1%></td>
					<td><%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Modificar</button>".html_safe, {:action => 'block', :doctor_id => d.doctor_id, :user_id => u.user_id} %></td>
				</tr>
			<% end %>
		<% end %>
	<% end %>
</table>