config/routes.rb
Rails.application.routes.draw do
  get 'administrations/index'

  get 'administrations/hours'

  get 'administrations/selec_doctor'

  get 'administrations/block'

  get 'administrations/add_block'

  get 'administrations/message1'

  get 'administrations/message2'

  get 'administrations/message3'

  get 'my_hours/mishoras'

  get 'my_hours/mishoras2'

  get 'my_hours/message1'

  get 'search/index'

  get 'take_hours/index'

  get 'take_hours/show'

  get 'take_hours/show2'

  get 'take_hours/show3'

  get 'take_hours/message1'

  get 'search_specialties/index'

  get 'search_medics/index'

  get 'users/index'

  get 'establishments/index'

  get 'establishments/show'

  get 'welcome/index'

  get 'reports/gestion' => 'reports#gestion'

  get 'reports/solicitudes' => 'reports#solicitudes'

  get 'reports/asistenciaAPS' => 'reports#asistenciaAPS'

  get 'reports/asistenciaGENERAL' => 'reports#asistenciaGENERAL'

  get 'reports/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  match ':controller(/:action(/:id))', :via => [:get, :post]
   root 'welcome#index'

end

app/models/attention_block.rb
class AttentionBlock < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/commune.rb
class Commune < ActiveRecord::Base
	has_many :establishments, :foreign_key => 'commune_id'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
	belongs_to :commune, :foreign_key => 'commune_id'
end

app/models/id_card_type.rb
class IdCardType < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/reserved_hour.rb
class ReservedHour < ActiveRecord::Base

	def self.crear(paciente_id, ab_id, hora_inicio, hora_fin)
		
		hora_inicio2 = Time.parse(hora_inicio).to_s(:db)
		hora_fin2 = Time.parse(hora_fin).to_s(:db)
		created = Time.zone.now.to_s(:db)
		updated = Time.zone.now.to_s(:db)
		sql = "INSERT INTO reserved_hours (patient_id, AB_ID, RH_START_TIME, RH_FINISH_TIME, RH_STATE, RH_ASSISTANCE, RH_DERIVED, created_at, updated_at) VALUES ('#{paciente_id}', '#{ab_id}', '#{hora_inicio2}', '#{hora_fin2}', true, false, false, '#{created}','#{updated}')"
		ActiveRecord::Base.connection.execute(sql)
	end


	def self.cancelar id
	sql = "UPDATE reserved_hours SET RH_STATE = false WHERE RH_ID = '#{id}'"
	ActiveRecord::Base.connection.execute(sql)
	end

	def self.confirmarAsistencia id_hora
		sql = "UPDATE reserved_hours SET RH_ASSISTANCE = true WHERE RH_ID = '#{id_hora}'"
		ActiveRecord::Base.connection.execute(sql)
	end
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def self.crear ict, comuna, names, paterno, materno, email

		created = Time.zone.now.to_s(:db)
		updated = Time.zone.now.to_s(:db)
		sql = "INSERT INTO users (ICT_ID, communes_ID, user_NAMES, user_LASTNAME1, user_LASTNAME2, user_EMAIL, created_at, updated_at) VALUES ('#{ict}', '#{comuna}', '#{names}', '#{paterno}','#{materno}','#{email}','#{created}','#{updated}')"
		ActiveRecord::Base.connection.execute(sql)
	end

	def self.actualizar_cumple fecha, id
		cumple = fecha["(1i)"]+"-"+fecha["(2i)"]+"-"+fecha["(3i)"]
		sql = "UPDATE users SET user_DATE_OF_BIRTH = '#{cumple}' WHERE user_id = '#{id}'"
		ActiveRecord::Base.connection.execute(sql)
	end

	def display_name
  		user_NAMES + " "+ user_LASTNAME1+ " "+ user_LASTNAME2
	end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def asistenciaAPS

		@horasReservadas = ReservedHour.find_by_sql("select * from reserved_hours")
		@usuarios = User.find_by_sql("select * from users")
		@pacientes = User.find_by_sql("select * from users u inner join patients p where p.user_id = u.user_id")
		@comuna = Commune.find_by_sql("select * from communes where commune_id = '#{@usuarios[0].commune_id}'")
		@ciudad = City.find_by_sql("select * from cities where city_id = '#{@comuna[0].city_id}'")
		@pacientes_horas = User.find_by_sql("select * from users u inner join patients p on p.user_id = u.user_id inner join reserved_hours rh on rh.patient_id = p.patient_id")
		@horas_especifico = ReservedHour.find_by_sql("select * from reserved_hours hr inner join attention_blocks ab on hr.AB_ID = ab.AB_ID inner join doctors doc on doc.doctor_id = ab.doctor_id inner join establishments est on est.EST_ID = doc.EST_ID inner join establishment_attention_types eat on eat.EST_ID = est.EST_ID inner join  attention_types at on at.AT_ID = eat.AT_ID")
		@as_primaria = ReservedHour.find_by_sql("select * from reserved_hours hr inner join attention_blocks ab on hr.AB_ID = ab.AB_ID inner join doctors doc on doc.doctor_id = ab.doctor_id inner join establishments est on est.EST_ID = doc.EST_ID inner join establishment_attention_types eat on eat.EST_ID = est.EST_ID inner join  attention_types at on at.AT_ID = eat.AT_ID where at.AT_attention_types = 'Primaria'")
		@prevision = Patient.find_by_sql("select * from patients e inner join previsions p on e.prevision_id = p.prevision_id")


  		@horasAPS = Array.new
  		@horasReservadas.each do |c|
    		if c.RH_ASSISTANCE == true
    			
    			@horasAPS << c
    		end
  		end

  end

  def asistenciaGENERAL
  	@prevision = Patient.find_by_sql("select * from patients e inner join previsions p on e.prevision_id = p.prevision_id")
  	@horas_especifico = ReservedHour.find_by_sql("select * from reserved_hours hr inner join attention_blocks ab on hr.AB_ID = ab.AB_ID inner join doctors doc on doc.doctor_id = ab.doctor_id inner join establishments est on est.EST_ID = doc.EST_ID inner join establishment_attention_types eat on eat.EST_ID = est.EST_ID inner join  attention_types at on at.AT_ID = eat.AT_ID")
    @pacientes_horas = User.find_by_sql("select * from users u inner join patients p on p.user_id = u.user_id inner join reserved_hours rh on rh.patient_id = p.patient_id")


    @num_pri = 0
    @num_sec = 0
    @num_ter = 0

  end


	def solicitudes
		@prevision = Patient.find_by_sql("select * from patients e inner join previsions p on e.prevision_id = p.prevision_id")
  		@horas_especifico = ReservedHour.find_by_sql("select * from reserved_hours hr inner join attention_blocks ab on hr.AB_ID = ab.AB_ID inner join doctors doc on doc.doctor_id = ab.doctor_id inner join establishments est on est.EST_ID = doc.EST_ID inner join establishment_attention_types eat on eat.EST_ID = est.EST_ID inner join  attention_types at on at.AT_ID = eat.AT_ID")
    	@pacientes_horas = User.find_by_sql("select * from users u inner join patients p on p.user_id = u.user_id inner join reserved_hours rh on rh.patient_id = p.patient_id")

	end

	def gestion


	end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users = User.order(:user_ID)
  end

  def new
  end

	def create
		#instanciar nuevo objeto
		ict = params[:user][:ICT_ID].to_i
		comuna = params[:user][:communes_id].to_i
		names = params[:user][:user_NAMES]
		paterno = params[:user][:user_LASTNAME1]		
		materno = params[:user][:user_LASTNAME2]		
		email = params[:user][:user_EMAIL]
		User.crear(ict, comuna, names, paterno, materno, email)

		redirect_to(:action => 'index')

	end

  def edit
	if current_user.user_ID != params[:id].to_i
		redirect_to users_index_path, notice: 'No puedes editar otro usuario'
	else
		@user = User.find_by_user_ID(params[:id])
	end
  end

  def delete
  end

  def show
	@user = User.find_by_users_ID(params[:id])
  end

  def update
		#instanciar nuevo objeto
		@user = User.find_by_users_ID(params[:id])
		@user.update_attributes(user_params)		

		#guardarlo con datos de form
		if @user.update_attributes(user_params)
			redirect_to(:action => 'show', :id => @user.users_ID )
		else	#si no
			render('edit')
		end
   end

   private
	#asigna todos los parámetros permitdos por permit de una 		mediante params
   def user_params
			params.require(:user).permit(:ICT_ID, :communes_ID, :users_NAMES, :users_LASTNAME1, :users_LASTNAME2, :users_EMAIL)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/my_hours_helper.rb
module MyHoursHelper
end

app/helpers/registrations_helper.rb
module RegistrationsHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/take_hours_helper.rb
module TakeHoursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/reports/asistenciaAPS.html.erb
<section id="contact-info">
	<div class="center">                
            <h2>Reporte Ingreso</h2>
            <p class="lead">Reporte del ingreso de pacientes por APS</p>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
					<center><h2 class="list-group">Estadistica APS</h2></center>
					<lu class="list-group">
						<lu class="list-group">							
							<li class="list-group-item">Asistencias: <b> <%= @asistencias_pri %> </b></li>
							<li class="list-group-item">Inasistencias: <b> <%= @asistencias_ter %> </b></li>
							<li class="list-group-item">Total pacientes: <b> <%= @asistencias_sec %> </b></li>
							
							
							
						</lu>
					</lu>
			                   
			</div>

				<div class="col-sm-6">
					<img src="http://www.definicionabc.com/wp-content/uploads/estadistica.jpg" class="img-rounded" alt="Cinque Terre">
				</div>

			</div>

	</div>
</section>
<section>


<div>
	<center><h2>Asistencia de Atención Primaria en Salud</h2></center>
	<table class = "listing" >
		<tr class = "header">
			<th>ID</th>
			<th>Nombres</th>
			<th>Apellido Paterno</th>
			<th>Apellido Materno</th>
			<th>Prevision</th>
			<th>Dir. Establecimiento</th>
			<th>Tipo de atención</th>
			<th>Hora ingreso</th>
			<th>Asistencia</th>
		</tr>
		
			<% @pacientes_horas.each do |phr| %>
				<% @prevision.each do |prev| %>	
				<% @as_primaria.each do |aspr| %>
					<% if prev.patient_id == phr.patient_id %>

						<% if aspr.patient_id == phr.patient_id %>
						<% if aspr.RH_ID == phr.RH_ID %>
							<tr>
								<td><%= phr.patient_id %></td>
								<td><%= phr.user_NAMES %></td>
								<td><%= phr.user_LASTNAME1 %></td>
								<td><%= phr.user_LASTNAME2 %></td>
								<td><%= prev.prevision_NAME %></td>
								<td><%= aspr.EST_ADDRESS %></td>
								<td><%= aspr.AT_attention_types %></td>
								<td><%= aspr.RH_START_TIME %></td>
								<td><%= phr.RH_ASSISTANCE %></td>
	
							</tr>
							<% end %>
						<% end %>	
					<% end %>	
				<% end %>	
			<% end %>
		<% end %>	
	</table>
</div>

</section>

app/views/reports/asistenciaGENERAL.html.erb
<section id="contact-info">
	<div class="center">                
            <h2>Reporte APS</h2>
            <p class="lead">Reporte del ingreso de pacientes por APS</p>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
					<center><h2 class="list-group">Estadistica total</h2></center>
					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Asistencias por tipo de atención</b></h3>
							
							<li class="list-group-item">Primaria: <b> <%= @asistencias_pri %> </b></li>
							<li class="list-group-item">Secundaria: <b> <%= @asistencias_sec %> </b></li>
							<li class="list-group-item">Terciaria: <b> <%= @asistencias_ter %> </b></li>
							
							
						</lu>
					</lu>

					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Total</b></h3>
							
							<li class="list-group-item">Asistentes: <b> 000 </b></li>
							<li class="list-group-item">Pacientes: <b> 0</b></li>
							
							
						</lu>
					</lu>
			                   
			</div>

				<div class="col-sm-6">
					<img src="http://www.definicionabc.com/wp-content/uploads/estadistica.jpg" class="img-rounded " alt="Cinque Terre" height=410px>
				</div>

			</div>

	</div>
</section>
<section>


<div>
	<center><h2>Asistencia de Atención Primaria en Salud</h2></center>
	<table class = "listing" >
		<tr class = "header">
			<th>ID Paciente</th>
			<th>Nombres</th>
			<th>Apellido Paterno</th>
			<th>Apellido Materno</th>
			<th>Prevision</th>
			<th>Dir. Establecimiento</th>
			<th>Tipo de atención</th>
			<th>Fecha ingreso</th>
			<th>Asistencia</th>
		</tr>
		<% @prevision.each do |prev| %>		
			<% @pacientes_horas.each do |phr| %>
					
				<% @horas_especifico.each do |espc| %>
					<% if prev.patient_id == phr.patient_id %>

						<% if espc.patient_id == phr.patient_id %>
							<% if espc.RH_ID == phr.RH_ID %>
							<tr>
								<td><%= phr.patient_id %></td>
								<td><%= phr.user_NAMES %></td>
								<td><%= phr.user_LASTNAME1 %></td>
								<td><%= phr.user_LASTNAME2 %></td>
								<td><%= prev.prevision_NAME %></td>
								<td><%= espc.EST_ADDRESS %></td>
								<td><%= espc.AT_attention_types %></td>
								<td><%= espc.RH_START_TIME %></td>
								<td><%= phr.RH_ASSISTANCE %></td>
	
							</tr>
							<% end %>	
						<% end %>	
					<% end %>	
				<% end %>	
			<% end %>
		<% end %>	
	</table>
</div>

</section>

app/views/reports/gestion.erb
<section id="contact-info">
	<div class="center">                
            <h2>Reporte de gestión</h2>
            <p class="lead"> Estadisticas generales</p>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
					
					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Pacientes y usuarios</b></h3>
							
							<li class="list-group-item">Usuarios registrados: <b> 0 </b></li>
							<li class="list-group-item">Pacientes activos: <b> 0 </b></li>
							<li class="list-group-item">ID Chilena: <b> 0 </b></li>
							<li class="list-group-item">ID Extrajera: <b> 0 </b></li>
							
							
						</lu>

						<lu class="list-group">
							<h3><b>Horas medicas</b></h3>
							
							<li class="list-group-item">Reservadas: <b> 0 </b></li>
							<li class="list-group-item">Canceladas: <b> 0 </b></li>
							<li class="list-group-item">Concretadas: <b> 0 </b></li>
							<li class="list-group-item">Pendientes: <b> 0 </b></li>
							
							
						</lu>
					</lu>

			                   
			</div>

			<div class="col-sm-6">
					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Medicos</b></h3>
							
							<li class="list-group-item">Activos: <b> 0 </b></li>
							<li class="list-group-item">N° Especialidades: <b> 0 </b></li>
						</lu>
						
						<lu class="list-group">
							<h3><b>Establecimientos</b></h3>
							
							<li class="list-group-item">Comunas abarcadas: <b> 0 </b></li>
							<li class="list-group-item">Establecimientos activos: <b> 0 </b></li>
							
							
						</lu>
					</lu>

					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Total</b></h3>		
							<li class="list-group-item">Pacientes: <b> 000 </b></li>
							
							
						</lu>
					</lu>
			                   
			</div>

			</div>

	</div>
</section>

app/views/reports/index.html.erb
<body>
	<section id="about-us">
		<div class = "container" >
			<div class="center wow fadeInDown">
				<h2> ¿Que desea administrar?</h2>
			</div>
			 <div class="main-login search-center">
				<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Reporte de Ingreso</button>".html_safe, reports_asistenciaAPS_path %>
				<%= link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Reporte de Gestion</button>".html_safe, reports_gestion_path %>
				<%=  link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Reporte de Asistencia General</button>".html_safe, reports_asistenciaGENERAL_path %>
				<%=  link_to "<button class= 'btn btn-primary btn-lg btn-block login-button' >Reporte de Solicitudes</button>".html_safe, reports_solicitudes_path %>
			</div>
		</div>
	</section>
</body>

app/views/reports/solicitudes.html.erb
<section id="contact-info">
	<div class="center">                
            <h2>Reporte de solicitudes interconsultas</h2>
            <p class="lead"> Número de solicitudes de interconsultas por establecimiento APS</p>
    </div>
	<div class="container">
		<div class="row">
			<div class="col-sm-6">
					<center><h2 class="list-group">Estadistica total</h2></center>
					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Solicitudes de interconsultas</b></h3>
							
							<li class="list-group-item">Usuario: <b> 0 </b></li>
							<li class="list-group-item">Paciente: <b> 0 </b></li>
							<li class="list-group-item"><b>Total:</b> 0 <b> </b></li>
							
							
						</lu>
					</lu>

					<lu class="list-group">
						<lu class="list-group">
							<h3><b>Total</b></h3>		
							<li class="list-group-item">Pacientes: <b> 000 </b></li>
							
							
						</lu>
					</lu>
			                   
			</div>

				<div class="col-sm-6">
					<img src="http://www.definicionabc.com/wp-content/uploads/estadistica.jpg" class="img-rounded " alt="Cinque Terre" height=410px>
				</div>

			</div>

	</div>
</section>
<section>


<div>
	<center><h2>Solicitudes de interconsultas por establecimiento APS</h2></center>
	<table class = "listing" >
		<tr class = "header">
			<th>ID Usuario</th>
			<th>ID Paciente</th>
			<th>Nombres</th>
			<th>Apellido Paterno</th>
			<th>Apellido Materno</th>
			<th>Prevision</th>
			<th>Establecimiento APS</th>
			<th>Solicitud de interconsulta</th>
		</tr>

		<% @pacientes_horas.each do |phr| %>
			<% @prevision.each do |prev| %>	
				<% @horas_especifico.each do |aspr| %>
					<% if prev.patient_id == phr.patient_id %>
						<% if aspr.patient_id == phr.patient_id %>
							<% if aspr.RH_ID == phr.RH_ID %>
							<tr>
								<td><%= phr.user_id %></td>
								<td><%= phr.patient_id %></td>
								<td><%= phr.user_NAMES %></td>
								<td><%= phr.user_LASTNAME1 %></td>
								<td><%= phr.user_LASTNAME2 %></td>
								<td><%= prev.prevision_NAME %></td>
								<td><%= aspr.EST_ADDRESS %></td>
								<td><%= aspr.RH_DERIVED %></td>
	
							</tr>
							<% end %>
						<% end %>
					<% end %>	
				<% end %>	
			<% end %>	
		<% end %>
		

		


	</table>
</div>

</section>