config/routes.rb
Rails.application.routes.draw do
  get 'administrations/index'

  get 'administrations/hours'

  get 'administrations/selec_doctor'

  get 'administrations/block'

  get 'administrations/add_block'

  get 'administrations/message1'

  get 'administrations/message2'

  get 'administrations/message3'

  get 'my_hours/mishoras'

  get 'my_hours/mishoras2'

  get 'my_hours/message1'

  get 'search/index'

  get 'take_hours/index'

  get 'take_hours/show'

  get 'take_hours/show2'

  get 'take_hours/show3'

  get 'take_hours/message1'

  get 'search_specialties/index'

  get 'search_medics/index'

  get 'users/index'

  get 'establishments/index'

  get 'establishments/show'

  get 'welcome/index'

  get 'reports/gestion' => 'reports#gestion'

  get 'reports/solicitudes' => 'reports#solicitudes'

  get 'reports/asistenciaAPS' => 'reports#asistenciaAPS'

  get 'reports/asistenciaGENERAL' => 'reports#asistenciaGENERAL'

  get 'reports/index'

  devise_for :users, :controllers => { registrations: 'registrations' }
  match ':controller(/:action(/:id))', :via => [:get, :post]
   root 'welcome#index'

end

app/models/attention_block.rb
class AttentionBlock < ActiveRecord::Base
end

app/models/city.rb
class City < ActiveRecord::Base
end

app/models/commune.rb
class Commune < ActiveRecord::Base
	has_many :establishments, :foreign_key => 'commune_id'
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
end

app/models/employee.rb
class Employee < ActiveRecord::Base
end

app/models/establishment.rb
class Establishment < ActiveRecord::Base
	belongs_to :commune, :foreign_key => 'commune_id'
end

app/models/id_card_type.rb
class IdCardType < ActiveRecord::Base
end

app/models/patient.rb
class Patient < ActiveRecord::Base
end

app/models/report.rb
class Report < ActiveRecord::Base
end

app/models/reserved_hour.rb
class ReservedHour < ActiveRecord::Base

	def self.crear(paciente_id, ab_id, hora_inicio, hora_fin)
		
		hora_inicio2 = Time.parse(hora_inicio).to_s(:db)
		hora_fin2 = Time.parse(hora_fin).to_s(:db)
		created = Time.zone.now.to_s(:db)
		updated = Time.zone.now.to_s(:db)
		sql = "INSERT INTO reserved_hours (patient_id, AB_ID, RH_START_TIME, RH_FINISH_TIME, RH_STATE, RH_ASSISTANCE, RH_DERIVED, created_at, updated_at) VALUES ('#{paciente_id}', '#{ab_id}', '#{hora_inicio2}', '#{hora_fin2}', true, false, false, '#{created}','#{updated}')"
		ActiveRecord::Base.connection.execute(sql)
	end


	def self.cancelar id
	sql = "UPDATE reserved_hours SET RH_STATE = false WHERE RH_ID = '#{id}'"
	ActiveRecord::Base.connection.execute(sql)
	end

	def self.confirmarAsistencia id_hora
		sql = "UPDATE reserved_hours SET RH_ASSISTANCE = true WHERE RH_ID = '#{id_hora}'"
		ActiveRecord::Base.connection.execute(sql)
	end
end

app/models/specialty.rb
class Specialty < ActiveRecord::Base
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

	def self.crear ict, comuna, names, paterno, materno, email

		created = Time.zone.now.to_s(:db)
		updated = Time.zone.now.to_s(:db)
		sql = "INSERT INTO users (ICT_ID, communes_ID, user_NAMES, user_LASTNAME1, user_LASTNAME2, user_EMAIL, created_at, updated_at) VALUES ('#{ict}', '#{comuna}', '#{names}', '#{paterno}','#{materno}','#{email}','#{created}','#{updated}')"
		ActiveRecord::Base.connection.execute(sql)
	end

	def self.actualizar_cumple fecha, id
		cumple = fecha["(1i)"]+"-"+fecha["(2i)"]+"-"+fecha["(3i)"]
		sql = "UPDATE users SET user_DATE_OF_BIRTH = '#{cumple}' WHERE user_id = '#{id}'"
		ActiveRecord::Base.connection.execute(sql)
	end

	def display_name
  		user_NAMES + " "+ user_LASTNAME1+ " "+ user_LASTNAME2
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
	@users = User.order(:user_ID)
  end

  def new
  end

	def create
		#instanciar nuevo objeto
		ict = params[:user][:ICT_ID].to_i
		comuna = params[:user][:communes_id].to_i
		names = params[:user][:user_NAMES]
		paterno = params[:user][:user_LASTNAME1]		
		materno = params[:user][:user_LASTNAME2]		
		email = params[:user][:user_EMAIL]
		User.crear(ict, comuna, names, paterno, materno, email)

		redirect_to(:action => 'index')

	end

  def edit
	if current_user.user_ID != params[:id].to_i
		redirect_to users_index_path, notice: 'No puedes editar otro usuario'
	else
		@user = User.find_by_user_ID(params[:id])
	end
  end

  def delete
  end

  def show
	@user = User.find_by_users_ID(params[:id])
  end

  def update
		#instanciar nuevo objeto
		@user = User.find_by_users_ID(params[:id])
		@user.update_attributes(user_params)		

		#guardarlo con datos de form
		if @user.update_attributes(user_params)
			redirect_to(:action => 'show', :id => @user.users_ID )
		else	#si no
			render('edit')
		end
   end

   private
	#asigna todos los parámetros permitdos por permit de una 		mediante params
   def user_params
			params.require(:user).permit(:ICT_ID, :communes_ID, :users_NAMES, :users_LASTNAME1, :users_LASTNAME2, :users_EMAIL)
		end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_helper.rb
module CatHelper
end

app/helpers/my_hours_helper.rb
module MyHoursHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/take_hours_helper.rb
module TakeHoursHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
    <!DOCTYPE html>
<html>
<head>

  <title>Clinica Usach</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body class = "homepage">

    <header id="header"> 
        <div class="top-bar">
            <div class="container">
                <div class="row">
                    <div class="col-sm-6 col-xs-4">
                        <div class="top-number"><p><i class="fa fa-phone-square"></i>  +0123 456 70 90</p></div>
                    </div>
                    <div class="col-sm-6 col-xs-8">
                        <div class="social">
                            <ul class="social-share">
                                <li><a href="https://www.facebook.com/Cl%C3%ADnica-Usach-1145784278796965/?__mref=message_bubble"><i class="fa fa-facebook"></i></a></li>
                                <li><a href="http://twitter.com/clinica_usach"><i class="fa fa-twitter"></i></a></li>
                                <li><a href="404.html"><i class="fa fa-skype"></i></a></li>
                            </ul>
                            <div class="search">
                                <form role="form">
                                    <input type="text" class="search-form" autocomplete="off" placeholder="Buscar">
                                    <i class="fa fa-search"></i>
                                </form>
                            </div>
                        </div>
                    </div>    
                </div>
            </div><!--/.container-->
        </div><!--/.top-bar-->
    </header>
    <nav class="navbar navbar-inverse" role="banner">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand"> <%= link_to image_tag("logo.png"), welcome_index_path %></a>
            </div>
            <div class="collapse navbar-collapse navbar-right">
                <ul class="nav navbar-nav">
                    <!--IF-->
                    <%- if current_page?(controller: 'welcome')%>
                        <li class = "active"><%= link_to "Inicio",  welcome_index_path %></li>
                    <!--ELSE-->
                    <%- else %>
                        <li><%= link_to "Inicio",  welcome_index_path %></li>
                    <% end -%><!-- END IF -->
                    <!--IF-->
                    <%- if user_signed_in?%>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= current_user.user_NAMES %> <i class="fa fa-angle-down"></i></a>
                            <ul class="dropdown-menu">
                                <li><%= link_to "Cerrar Sesión", destroy_user_session_path, :method => :delete %></li>
                                <li><%= link_to "Mis Horas", my_hours_mishoras_path %></li>
                            </ul>
                        </li>
                    <!--ELSE-->
                    <%- else %>
                        <!--IF-->
                        <%- if current_page?(controller: 'registrations')%>
                            <li class = "active"><%= link_to "Iniciar sesión",  new_user_session_path %></li>
                        <%- else %>
                            <li><%= link_to "Iniciar sesión",  new_user_session_path %></li>
                        <% end -%><!-- END IF -->
                    <% end -%><!-- END IF -->
                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">Servicios <i class="fa fa-angle-down"></i></a>
                        <ul class="dropdown-menu">
                            <li><%= link_to "Reservar Hora Médica", search_index_path %></li>
                            <%- if user_signed_in?%>
                                <%- if current_user.admin? || current_user.functionary?%>
                                    <li><%= link_to "Administrar", administrations_index_path %></li>
                                    <li><%= link_to "Reportes", reports_index_path %></li>
                                <% end -%>
                            <% end -%>
                        </ul>
                    </li>
                    <li><a href="#">Acerca de Nosotros</a></li>
                    <!--IF-->
                    <%- if current_page?(controller: 'establishments')%>
                        <li class = "active"><%= link_to "Ubicaciones",  establishments_index_path %></li>
                    <%- else %>   
                        <li><%= link_to "Ubicaciones",  establishments_index_path %></li>
                    <% end -%><!-- END IF -->
                    <li><a href="#">Noticias</a></li> 
                    <li><a href="#">Contacto</a></li>                        
                </ul>
            </div>
        </div><!--/.container-->
    </nav><!--/nav-->
<%= yield %>

    <footer id="footer" class="midnight-blue">
        <div class="container">
            <div class="row">
                <div class="col-sm-6">
                    &copy; 2013 <a target="_blank" href="http://shapebootstrap.net/" title="Free Twitter Bootstrap WordPress Themes and HTML templates">ShapeBootstrap</a>. All Rights Reserved.
                </div>
                <div class="col-sm-6">
                    <ul class="pull-right">
                        <li><a href="#">Inicio</a></li>
                        <li><a href="#">Acerca de Nosotros</a></li>
                        <li><a href="#">Faq</a></li>
                        <li><a href="#">Contacto</a></li>
                    </ul>
                </div>
            </div>
        </div>
    </footer><!--/#footer-->
</body>
</html>